### ISSUE TITLE
improvement(ram): improve ram size

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1028]
STR:
- so when we do cargo run --release, it takes around 1.24gb in ram

we should improve that

telegram desktop takes up around 200mb, and discord around 150mb

**Comment by dariusc93** [comment]
Keep in mind it varies on many conditions (as well as platforms it is running on), as Ive seen telegram get as high as 2GB and discord as high as 1GB, all of which may vary on what is being cached/stored in memory, connections, how many chats are loaded, etc).

However the ram usage (on warp side at least) is mostly a number of connections being opened (see https://github.com/Satellite-im/Warp/issues/67, and https://github.com/Satellite-im/Warp/issues/68 on a small solution) and usually the usage stops over time but the memory remains allocated to reuse for other connections as well as memory for spawned task. Avg memory usage I see when using the command line over 24hrs is around 500mb while bootstrapping the public network with the lowest being about 130mb and highest being about 4gb (could get higher but unlikely in most cases since this case was due to some stuff i was testing out). Without bootstrapping or disabling discovery and connecting directly, its usually a lot less (usually about 30MB) but bound to increase as connections increase, though I do have solutions to handle this more effectively (though i might make pr in uplink in the near future to enable a separate flag to disable some of the discovery options done in exchange for direct connections as an experiment although this is more suited for mobile environments but may also be helpful for those with network restrictions with PCs too).

For uplink, some key points to pay attention to might be (will be updated over time):
- Checking how memory usage is impacted while loading/unloading extensions (since this is calling native libraries, loading/unloading without a proper cleanup might cause memory leaks)
- How the state (within uplink) handles or retains data
- Determine if memory within dioxus remains allocated on heap after the data is removed/dropped
- Memory when switching between different parts of the app

I would not rely on a mock environment completely for uplink to determine memory usage checks but could still help detects if there is any slight increase overtime without any decrease when switching between various of stuff in the UI

**Comment by sdwoodbury** [comment]
@stavares843 it would be helpful if you could attach your `.uplink` directory and the password.

Aside from that, I did notice on my machine that RAM grows by a few MB a few times a minute. I noticed the same behavior with the `blink-webrtc-cil` and on Uplink, commenting out the obvious places - warp runner, chats, storage, and extensions - didn't change the behavior. I can leave `blink-webrtc-cil` on for a while and see if the RAM usage levels off and if so, at what level. 

From what Darius said, it looks like this is probably normal stuff from IPFS. And since we're using that instead of a server, we probably can't compare ourselves to Discord and  Telegram.

**Comment by stavares843** [comment]
closing to be improved in the future

**Comment by sdwoodbury** [comment]
I left `blink-webrtc-cil` on overnight and the Memory usage is up to 2.6GB. There's probably some IPFS setting to make it use less.
