### ISSUE TITLE
chore(state): Investigate how we can not lose all chats when changes are made to state 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1158]
**Issue:**
Sometimes when you switch to a PR all of your messages and chats will be missing. We thought this was due to any changes in state but Kevin was thinking it could be due to his changing the serialized state from a hashset to a hashmap. This ticket is to further investigate that 

![image](https://github.com/Satellite-im/Uplink/assets/93608357/c936a046-54b8-4568-bae2-6f01e173f36b)

**Comment by lgmarchi** [comment]
> **Issue:** Sometimes when you switch to a PR all of your messages and chats will be missing. We thought this was due to any changes in state but Kevin was thinking it could be due to his changing the serialized state from a hashset to a hashmap. This ticket is to further investigate that
> 
> ![image](https://user-images.githubusercontent.com/93608357/262800318-c936a046-54b8-4568-bae2-6f01e173f36b.png)

The reason is exactly because, when you change branches, and state.json has a field that does not exist in uplink state, it will erase all data from state.json and does not crash app. 

One solution, could be, chats in sidebar be in other json file, and any other changes in uplink state, will not erase data from chats in sidebar.
