### ISSUE TITLE
bug(chat): Embedded videos will return error 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1408]
**Issue:**
When you send a youtube link in chat and go to play it, the video player will show an error 

**OS:**
All

**Screenshot:**
![image](https://github.com/Satellite-im/Uplink/assets/93608357/962080ef-dcf7-4a69-88e6-2d7a71c7e873)

**Comment by stavares843** [comment]
still happens

**Comment by WanderingHogan** [comment]
I am going to relinquish this ticket.

I suspect it having something to do with what each individual webview allows OR something to do with the protocol dioxus sets, but I am not sure. 

Dioxus sets the protocol to 'dioxus' on mac, but not on windows.
mac:
<img width="449" alt="Screenshot 2023-11-08 at 9 15 17 PM" src="https://github.com/Satellite-im/Uplink/assets/2993032/993307af-e6d4-4ff2-987a-77f9bb2944ed">

here is the same thing in windows (thank you @XileHorizon ):
![image](https://github.com/Satellite-im/Uplink/assets/2993032/0af5f565-2e7b-4899-b823-9ab6dcc02fc4)



Some videos have this error from the iframe in console:
<img width="510" alt="Screenshot 2023-11-08 at 9 08 38 PM" src="https://github.com/Satellite-im/Uplink/assets/2993032/760cdb3d-1f4b-4793-b72d-9384f812a407">

Since this particular video, https://www.youtube.com/watch?v=w3rQ3328Tok, works embedded on windows, which uses chrome/edge webview, which is not present in safari: https://caniuse.com/mdn-http_headers_content-security-policy_require-trusted-types-for
