### ISSUE TITLE
bug(Windows): Spamming images in chat will cause a crash

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1418]
**Issue:**
There seems to be a crash happening on Windows when the user spams images in chat. @XileHorizon has been able to replicate multiple times. Asked Kev to throw the flow/crash report/what image he is using in this ticket to hopefully help debug this a little easier 

**OS:**
Windows

**Comment by XileHorizon** [comment]
When I attempt to paste a screenshot into a chat, the app behaves unexpectedly. Another unrelated bug causes multiple instances of the same image to be pasted into the chat input when copying and pasting an image. The app becomes unresponsive when multiple images or videos are sent.

**Steps to Reproduce:**
1. Open the application.
2. Copy an image or take a screenshot.
3. Paste it into a chat.
4. Send.
5. Observe the issues described above.

**Alternate Steps (1/2)**
1. Open the application.
2. Drag and drop multiple images or videos into a chat.
3. Send.
4. Observe the issues described above.

**Alternate Steps (2/2)**
1. Open the application.
2. Drag and drop a single video file into a chat.
3. Send
4. Observe the issues described above.

**Files Tested**
https://drive.google.com/drive/folders/16Xlrdjpo4MXvjCgfpSJrSaF09dvMVplM?usp=sharing

**Expected Behavior:**
Pasting images and videos should work smoothly without causing the application to hang or malfunction.

**Actual Behavior:**
- Multiple instances of the same image or video are pasted.
- The application becomes unresponsive when sending multiple images or videos.
- Closing the app makes it unusable until the 'state.json' file is deleted.

**Additional Information:**
- Operating System: Windows 11 22H2.

**Logs:**
Here are some relevant log entries from the dev console:
```〇 2023-10-26 11:50:50
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:50
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:50
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:50
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:56
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:57
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:57
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:57
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:57
DEBUG
»
state::mutate: SetChatAttachments
〇 2023-10-26 11:50:59
DEBUG
»
state::mutate: ClearChatAttachments
〇 2023-10-26 11:50:59
DEBUG
»
WARP CMD: RayGun { SendMessage }
〇 2023-10-26 11:50:59
ERROR
»
failed to send warp_event
〇 2023-10-26 11:50:59
ERROR
»
failed to send warp_event
〇 2023-10-26 11:50:59
ERROR
»
failed to send warp_event
〇 2023-10-26 11:50:59
ERROR
»
failed to send warp_event
〇 2023-10-26 11:50:59
ERROR
»
failed to send warp_event
〇 2023-10-26 11:51:00
ERROR
»
failed to send warp_event
〇 2023-10-26 11:51:00
ERROR
»
failed to send warp_event
〇 2023-10-26 11:51:00
ERROR
»
failed to send warp_event
〇 2023-10-26 11:51:00
ERROR
»
failed to send warp_event
〇 2023-10-26 11```

**Comment by phillsatellite** [comment]
@XileHorizon can you still replicate this?

**Comment by XileHorizon** [comment]
@phillsatellite I think this issue may have been resolved. I have tested with some of the same files that I had issues with before and it appears to be working properly now.
