### ISSUE TITLE
chat(feat): Add ability to tag friend in chat 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1460]
**Task:**
We want to be able to tag people in chat and them get notified for it so if someone was to tag me it would look like "hey @phill" and I would get a notification that someone directly tagged me in the chat 

**Screenshot:**
<img width="367" alt="Screenshot 2023-11-06 at 4 31 57 PM" src="https://github.com/Satellite-im/Uplink/assets/93608357/9d2f1424-c465-4cca-8b70-b3aa38df0fb4">

**Comment by tooshel** [comment]
A good first pass here is just making it so that when you type @ and a few characters you get a dropdown of users and it can autofill . . . sorta like how an emoji works.  For now don't worry about notifications so we don't have a way to notify outside of the entire group. 

![image](https://github.com/Satellite-im/Uplink/assets/223338/ea4b48cc-1bd5-48ee-8cbd-1fc59bd7c884)
