### ISSUE TITLE
bug(crash): failed to get response from warp_runner: Canceled

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Uplink#1552]
STR:
- go to dev or any branch
- compile with or without release flag
- app crashes
- delete .uplink dir, build again keeps crashing

crash already exists for a few weeks

darius note
https://github.com/Satellite-im/Uplink/blob/f884017660abff4e1f65993326eee4796fccd0bb/common/src/warp_runner/manager/commands/multipass_commands.rs#L143-L145

crash log
[28-11-2023_00-45-32.log](https://github.com/Satellite-im/Uplink/files/13482506/28-11-2023_00-45-32.log)

macOS, m1

**Comment by dariusc93** [comment]
Just to note, it seems dropping the oneshot here may cause a panic (although im not on reproducing it, maybe @stavares843 can chime in on that) since we are expecting it not to drop, but in the lines above, it does drop. Would need to look more into it but it may be a race between `handle_multipass_cmd` and `handle_login` when trying to login. Probably would need to split that logic so we wouldnt need to ignore those commands in `handle_multipass_cmd`

**Comment by stavares843** [comment]
thanks @dariusc93 🔨

**Comment by sdwoodbury** [comment]
I couldn't reproduce 
![image](https://github.com/Satellite-im/Uplink/assets/8636602/bc88e2fb-1b26-4037-9b91-e4fd55b8e71a)

note that `warp_runner/mod.rs` has a `handle_login` function where `CreateIdentity` is handled. That's why `warp_runner/manager` doesn't handle it.

**Comment by stavares843** [comment]
no longer happens probably fixed here https://github.com/Satellite-im/Uplink/pull/1570


closing
