### ISSUE TITLE
task(chat): Incoming messages should not affect scroll 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#1566]
**Task:**
- [ ] While scrolling up and reading higher messages in the chat, if any incoming messages are received the scroll position should not be affected and keep its place. The button Scroll to Bottom should say New Message Below when new message is received 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/8eb15bc3-43d3-4209-a768-761d6817c5a2

**Comment by sdwoodbury** [comment]
i believe this bug was introduced here: https://github.com/Satellite-im/Uplink/pull/1530 but am not completely sure yet. In any case. the chat behavior isn't being updated when the user scrolls up. That's why when a message is received, the view scrolls to the bottom. 

The reason for doing #1530 was to make the scroll button appear earlier, such as when a large image is in the chat and it takes some scrolls to get halfway through the image.
