### ISSUE TITLE
Chat - Raygun extension is unavailable 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#323]
**Issue:** Sometimes it seems like messages arent coming through after logging back into the app, and then if you log out and back in again chat will update and the messages will finally come through. Also noticed when this happens sometimes this will appear in chat `failed to initialize conversations: RayGun extensions in unavailable`

**Screenshot**
![image](https://user-images.githubusercontent.com/93608357/220478163-76f3b4bd-d28e-442e-bae8-8626e6749cee.png)

**Comment by dariusc93** [comment]
While that error does happens, it does retry again per https://github.com/Satellite-im/Uplink/blob/dev/ui/src/main.rs#L737-L758 (which is why you see the initialize command in the log again), so i wouldnt call it a problem, but probably should wait until raygun is available before performing any chat task. Maybe downgrade the error to a warning if its `Error::RayGunExtensionUnavailable` and only upgrade it to an error after so many tries (or ignore it until after so many tries then show it)?

**Comment by sdwoodbury** [comment]
Agreed that the attached log doesn't indicate a problem because Uplink automatically retries in this case.
