### ISSUE TITLE
Chat - Chat bar size will persist after sending a large message

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#458]
**Issue:** When you are sending a large message, after you hit send the input box in chat will remain the same size as it was when you had the message typed up 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/225359653-a60719b7-4688-4a04-8c0b-d2f319e392c6.mov

**Comment by Flemmli97** [comment]
i fixed that issue in #445. forgot to point it out there.
should i create a new PR just for that again?
the fix is at
[https://github.com/Satellite-im/Uplink/pull/445/files#diff-6c3d4f34c9eca5781fecc62f1c2baf341f5a244271e0e1a291709c19cfb41973R85](https://github.com/Satellite-im/Uplink/pull/445/files#diff-6c3d4f34c9eca5781fecc62f1c2baf341f5a244271e0e1a291709c19cfb41973R85)
