### ISSUE TITLE
Ul - Usernames appear as DID key 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#464]
**Issue:** When you add someone, sometimes in Pending/All Friends/or chat&sidebar they will appear as a blank profile picture with their DID appearing as they're name. This flow below will get the app to update the UI to the correct information 
 
1. User A adds User B 
2. User B appears as "z6M...Zcd" 
3. User B updates either their pfp, username, or status 
4. After this all of Users B information appears fine on Users A side

**OS**
-MacOS
-Windows
-Linux

**Screenshot:**
<img width="343" alt="Screenshot 2023-03-15 at 5 35 32 PM" src="https://user-images.githubusercontent.com/93608357/225450028-fdab6be0-e836-4604-b103-57251beeb135.png">

**Comment by dariusc93** [comment]
Related to #275 (which this issue is related to #278), this is done if the user have not been discovered yet, which could be for plenty of reasons (they werent online at the time of the request, they are but unable to be discovered due to networking related issues, etc). Ideally in the near future, a optional third party service will be used apart of discovery to get the identity by the did and pull it in and allow that to be optionally used for stuff like this (when that time comes anyway - last thing one want is a hard dependency on single location that could be a single point of failure), but what could be done in the UI could still be related to the issue referenced in the beginning. Possibly have something in the `Identity` wrapper to mark it as incomplete, use a task to get those incomplete identities and pass it into `MultiPass::get_identity` in an attempt to "refresh" it so make sure it is complete.

**Comment by tooshel** [comment]
This seems to happen even when both users are online.
