### ISSUE TITLE
Friends - Disable friends button after request sent 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#554]
**Issue:** On friends, after you add someone it will clear the did from the text input, but if you continue to keep hitting _Send_ it will keep sending duplicate friend request to that user 

**STR**
Paste DID into input box 
Send request 
Keep hitting send

**Comment by WanderingHogan** [comment]
![Screenshot 2023-04-10 at 10 40 28 AM](https://user-images.githubusercontent.com/2993032/230948328-c7b93c67-a047-459e-be5c-baa091010c31.png)
 Here is what it looks like after you send a friend request, it clears the input but its still in state with an active button and it re-sends the request on button click, instead of the default disabled button state
