### ISSUE TITLE
Chat - Indicate that file is downloading 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#562]
**Issue:**
When you download a file from chat it takes a good bit of time for the download to save to your computer. If you try to open it before its done you will get an error that file cannot be opened. Once you give it a couple more minutes file will finish downloading and user can open it

**OS:**
- MacOS
- Linux
- Window

**Comment by dariusc93** [comment]
This is due to bitswap and how it attempts to query peers and exchange blocks. Under experimental node (or any node with little traffic), this shouldnt be a problem while on public nodes, this does happen a bit more (and sometimes can take longer if one cannot direct connect through relay). It should work fine locally due to it being local and very little to query. This will likely change in the next week or two to make things more efficient.

**Comment by phillsatellite** [comment]
With Darius's input given above Hogan and I decided to test this on dev with an experimental-node and we both were able to successfully send and download the entire file that was sent in chat. (We also tested changing the location of where that file would be saved to and file would successfully save)
