### ISSUE TITLE
Friends - Somtimes Sender is not updated when pending request is accepted 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#615]
**Issue:**
When User A sends User B a friend request and User B accepts, sometimes User A will not be updated and request will remain in pending. 

**OS:**
MacOS
Linux
Windows

**Screenshots:**
In this scenario, Linux sent a friend request to PhillMacAir and PhillMacAir accepted
<img width="660" alt="Screenshot 2023-04-10 at 12 43 09 PM" src="https://user-images.githubusercontent.com/93608357/230950575-e040822a-81ae-40bb-963a-c190f80c85c2.png">

On Linux side request still appears as pending and has yet to update. If PhillMacAir was to remove Linux as a friend, request would still remain as pending to Linux 
<img width="667" alt="Screenshot 2023-04-10 at 12 43 04 PM" src="https://user-images.githubusercontent.com/93608357/230950592-38df9146-feec-4e40-93c2-1758d41b1e1c.png">

**Comment by dariusc93** [comment]
This is likely due to the [public] relay data restrictions. Although the data sent should be small enough to go through the relay (in the event upnp, and direct connection failing and falling back to the relay), it may be that the other end is either slowly transmitting or is failing to transmit. I will look into this (especially since i know direct connection isnt successful for @phillsatellite, so i may do additional testing with him to get additional log information to investigate on how to improve that upstream). Using the experimental flag should improve on this though due to the higher data limit.
